name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  pr_number:
    description: 'Your input description here'
    required: true
  notion_token:
    description: 'Your input description here'
    required: true
  octokit_token:
    description: 'Your input description here'
    required: true
  storyUrl:
    description: 'Your input description here'
    required: true
    default: 'https://storybook.localhost'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
